export const TOPICS = [
  "Arrays",
  "Arrays Part-II",
  "Arrays Part-III",
  "Arrays Part-IV",
  "Linked List",
  "Linked List Part-II",
  "Linked List and Arrays",
  "Greedy Algorithm",
  "Recursion",
  "Recursion and Backtracking",
  "Binary Search",
  "Heaps",
  "Stack and Queue",
  "Stack and Queue Part-II",
  "String",
  "String Part-II",
  "Binary Tree",
  "Binary Tree part-II",
  "Binary Tree part-III",
  "Binary Search Tree",
  "Binary Search Tree Part-II",
  "Binary Trees[Miscellaneous]",
  "Graph",
  "Graph Part-II",
  "Dynamic Programming",
  "Dynamic Programming Part-II",
  "Trie",
] as const;

export type Topic = typeof TOPICS[number];

